version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile
      context: ./docker
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - PHP_ENABLE_XDEBUG
    ports:
      - '8000:80'
